ALTER TABLE IF EXISTS MASTER_KEY_REPOSITORY
    DROP CONSTRAINT FK_MASTER_KEY_OWNER;

ALTER TABLE IF EXISTS MESSAGE_REPOSITORY
    DROP CONSTRAINT IF EXISTS FK_MESSAGE_OWNER;

ALTER TABLE IF EXISTS MESSAGE_REPOSITORY
    DROP CONSTRAINT IF EXISTS FK_USED_MASTER_KEY;

DROP TABLE IF EXISTS MASTER_KEY_REPOSITORY;

DROP TABLE IF EXISTS MESSAGE_REPOSITORY;

DROP TABLE IF EXISTS USER_REPOSITORY;

CREATE TABLE IF NOT EXISTS MASTER_KEY_REPOSITORY
(
    MASTER_KEY_ID int NOT NULL,
    MASTER_KEY_NAME varchar(20),
    MASTER_KEY text NOT NULL,
    MASTER_KEY_OWNER varchar(30) NOT NULL,
    CONSTRAINT PK_MASTER_KEY_ID PRIMARY KEY (MASTER_KEY_ID)
);
CREATE TABLE IF NOT EXISTS MESSAGE_REPOSITORY
(
    MESSAGE_ID int NOT NULL,
    MESSAGE_NAME varchar(20),
    MESSAGE text NOT NULL,
    USED_MASTER_KEY_ID int NOT NULL,
    MESSAGE_OWNER varchar(30) NOT NULL,
    CONSTRAINT PK_MESSAGE_ID PRIMARY KEY (MESSAGE_ID)
);
CREATE TABLE IF NOT EXISTS USER_REPOSITORY
(
    USER_NAME varchar(30) NOT NULL ,
    USER_PASSWORD varchar(50) NOT NULL,
    CONSTRAINT PK_USER_NAME PRIMARY KEY (USER_NAME)
);

ALTER TABLE MASTER_KEY_REPOSITORY
    ADD CONSTRAINT FK_MASTER_KEY_OWNER FOREIGN KEY (MASTER_KEY_OWNER)
        REFERENCES USER_REPOSITORY (USER_NAME);

ALTER TABLE MESSAGE_REPOSITORY
    ADD CONSTRAINT FK_USED_MASTER_KEY FOREIGN KEY (USED_MASTER_KEY_ID)
        REFERENCES MASTER_KEY_REPOSITORY (MASTER_KEY_ID);

ALTER TABLE MESSAGE_REPOSITORY
    ADD CONSTRAINT FK_MESSAGE_OWNER FOREIGN KEY (MESSAGE_OWNER)
        REFERENCES USER_REPOSITORY (USER_NAME);