CREATE TABLE MASTER_KEY_REPOSITORY
(
    MASTER_KEY_ID int,
    MASTER_KEY_NAME varchar(20),
    MASTER_KEY text
);
CREATE TABLE MESSAGE_REPOSITORY 
(
    MESSAGE_ID int,
    MESSAGE_NAME varchar(20),
    MESSAGE text,
    USED_MASTER_KEY text
);